language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
branch: master
